version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "topic-modeling"
          ContainerPort: 5000
Hooks:
  - AfterAllowTestTraffic: "arn:aws:lambda:us-east-1:143176219551:function:churn_application"